### ISSUE TITLE
Resolve the pac script error

### ISSUE THREAD

**Issue by avwo** [TooTallNate/node-pac-resolver#16]
Code:
```
var fs = require('fs');
var pac = require('pac-resolver');

var FindProxyForURL = pac(fs.readFileSync('proxy.pac', 'utf8'));

FindProxyForURL('http://foo.com/', 'foo.com', function (err, res) {
  if (err) throw err;
  console.log(res);
    // → "DIRECT"
});
```

proxy.pac:
```
var FindProxyForURL = function(init, profiles) {
    return function(url, host) {
        "use strict";
        var result = init, scheme = url.substr(0, url.indexOf(":"));
        do {
            result = profiles[result];
            if (typeof result === "function") result = result(url, host, scheme);
        } while (typeof result !== "string" || result.charCodeAt(0) === 43);
        return result;
    };
}("+google", {
    "+google": function(url, host, scheme) {
        "use strict";
        if (/(?:^|\.)google\.com$/.test(host)) return "+internal-vf";
        return "DIRECT";
    },
    "+internal-vf": function(url, host, scheme) {
        "use strict";
        if (host === "127.0.0.1" || host === "::1" || host.indexOf(".") < 0) return "DIRECT";
        return "PROXY 127.0.0.1:8123";
    }
});
```

Throws error:
```
/xxx/node_modules/.1.0.3@degenerator/index.js:53
      names.push(path.node.id.name);
                             ^

TypeError: Cannot read property 'name' of null
    at Context.visitFunction (/xxx/node_modules/.1.0.3@degenerator/index.js:53:30)
    at Context.invokeVisitorMethod (/xxx/node_modules/.0.9.1@ast-types/lib/path-visitor.js:344:49)
    at Visitor.PVp.visitWithoutReset (/xxx/node_modules/.0.9.1@ast-types/lib/path-visitor.js:196:32)
    at visitChildren (/xxx/node_modules/.0.9.1@ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/xxx/node_modules/.0.9.1@ast-types/lib/path-visitor.js:204:20)
    at visitChildren (/xxx/node_modules/.0.9.1@ast-types/lib/path-visitor.js:246:25)
    at Visitor.PVp.visitWithoutReset (/xxx/node_modules/.0.9.1@ast-types/lib/path-visitor.js:204:20)
    at NodePath.each (/xxx/node_modules/.0.9.1@ast-types/lib/path.js:101:26)
    at visitChildren (/xxx/node_modules/.0.9.1@ast-types/lib/path-visitor.js:219:18)
    at Visitor.PVp.visitWithoutReset (/xxx/node_modules/.0.9.1@ast-types/lib/path-visitor.js:204:20)
```

**Comment by TooTallNate** [comment]
Thanks for the report! There was a bug in `node-degenerator` that wasn't handling the pattern you were doing. Should be fixed now.

**Comment by haohaolee** [comment]
Hi, I just want to mention, even if this issue is fixed in `node-degenerator`, it still doesn't work for `pac-resolver` for this very case, since `FindProxyForURL` doesn't get translated into generator, hence there will be an error in `co`
```node test.js
/Users/haoli/projects/node-pac-resolver/node_modules/co/index.js:62
      setImmediate(done.bind(ctx, err, res));
                        ^

TypeError: done.bind is not a function
    at exit (/Users/haoli/projects/node-pac-resolver/node_modules/co/index.js:62:25)
    at next (/Users/haoli/projects/node-pac-resolver/node_modules/co/index.js:85:18)
    at /Users/haoli/projects/node-pac-resolver/node_modules/co/index.js:56:5
    at FindProxyForURL (/Users/haoli/projects/node-pac-resolver/index.js:97:5)
    at Object.<anonymous> (/Users/haoli/projects/node-pac-resolver/test.js:6:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)```

**Comment by haohaolee** [comment]
But giving it another thought, it is actually hard to translate such kind of code to async. Say we have the following code:
```
var func = function(){
    return function(url, host){
        if (isInNet(dnsResolve(host), "172.16.0.0", "255.240.0.0"))
            return "DIRECT";
        return "PROXY 127.0.0.1:8123";
    };
}();

function FindProxyForURL(url, host)
{
    return func(url, host);
}
```
If it can be translated into
```
var func = function(){
    return function*(url, host){
        if (yield isInNet(yield dnsResolve(host), "172.16.0.0", "255.240.0.0"))
            return "DIRECT";
        return "PROXY 127.0.0.1:8123";
    };
}();

function* FindProxyForURL(url, host)
{
    return yield func(url, host);
}
```

Currently, I cannot find a way to translate the code into what we need

What do you think?
