### ISSUE TITLE
tests failing after recent update to facebook/regenerator module

### ISSUE THREAD

**Issue by diffsky** [TooTallNate/node-pac-resolver#8]
```
opacus: ~/node-pac-resolver (master)
$ npm test

> pac-resolver@1.2.5 test /Users/mhadley/node-pac-resolver
> mocha --reporter spec


/Users/mhadley/node-pac-resolver/node_modules/regenerator/main.js:55
        path.join(__dirname, "runtime.js"), "utf-8"
             ^
TypeError: Cannot call method 'join' of undefined
    at Function.compile (/Users/mhadley/node-pac-resolver/node_modules/regenerator/main.js:55:14)
    at Object.<anonymous> (/Users/mhadley/node-pac-resolver/index.js:36:41)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/mhadley/node-pac-resolver/test/test.js:6:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/mhadley/node-pac-resolver/node_modules/mocha/lib/mocha.js:185:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/mhadley/node-pac-resolver/node_modules/mocha/lib/mocha.js:182:14)
    at Mocha.run (/Users/mhadley/node-pac-resolver/node_modules/mocha/lib/mocha.js:394:31)
    at Object.<anonymous> (/Users/mhadley/node-pac-resolver/node_modules/mocha/bin/_mocha:394:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
npm ERR! Test failed.  See above for more details.
```

Looks likes commit https://github.com/facebook/regenerator/commit/1efe26ae772409548098d91b92787f50c0d42851 is causing breakages, as seen in https://github.com/facebook/regenerator/issues/179

**Comment by diffsky** [comment]
This has been fixed downstream https://github.com/facebook/regenerator/commit/d965625fc5b99d53456026a742d1eaa185841e00
